### PR TITLE
RLS v1.1.1

### PR DESCRIPTION
**Pull request by simonjayhawkins**

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
this one still failing. will push commit to ignore shortly (assuming other builds pass)

```
=========================== short test summary info ===========================
FAILED test_venv/lib/site-packages/pandas/tests/io/parser/test_common.py::test_file_descriptor_leak[c_high]
= 1 failed, 63966 passed, 7374 skipped, 1049 xfailed, 6 xpassed, 14 warnings in 529.35s (0:08:49) =
```

**Comment by simonjayhawkins** [comment]
Thanks Tom. I don't have access to PyPI. can you also upload. (or I can do it if given access. my PyPI username is simonjayhawkins)

**Comment by TomAugspurger** [comment]
@jreback or @jorisvandenbossche can you add Simon as a maintainer on PyPI

**Comment by jorisvandenbossche** [comment]
I am not an admin on PyPI, so can't add anyone

**Comment by jreback** [comment]
yep hang on a minute

**Comment by simonjayhawkins** [comment]
Thanks Jeff. notification from PyPI recieved. docs built just about to upload them. will checkout PyPI shortly.

**Comment by simonjayhawkins** [comment]
@TomAugspurger can you restart the two fails on master. I think flaky. failed a couple of times b4 https://github.com/MacPython/pandas-wheels/pull/93#issuecomment-676589986

**Comment by TomAugspurger** [comment]
Restarted.

**Comment by simonjayhawkins** [comment]
Thanks Tom. restarted builds passed and wheels in staging.

**Pull request merged**
