### PR TITLE
binary only for cryptography

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/pandas-dev/pandas/issues/26589

(maybe).

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Alternatively, I think we just don't install moto and skip those tests.

**Comment by jreback** [comment]
thanks @TomAugspurger

**Comment by jreback** [comment]
actually prob need to push this to the daily branch

**Comment by TomAugspurger** [comment]
Will do.

**Comment by jreback** [comment]
I updated the daily branch

**Pull request merged**
