### PR TITLE
Daily 3.8

### PR DESCRIPTION
**Pull request by TomAugspurger**
This is against daily.

Will also need one for master.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @jbrockmendel.

**Comment by TomAugspurger** [comment]
Seems like daily has been failing for a while: https://travis-ci.org/MacPython/pandas-wheels/builds/587339414. Haven't had a chance to look closely.

**Comment by TomAugspurger** [comment]
Taking a closer look now. Will ping you if needed @jbrockmendel.

**Comment by TomAugspurger** [comment]
https://travis-ci.org/MacPython/pandas-wheels/builds/597816689?utm_source=github_status&utm_medium=notification got the right numpy.

Failed installing CFFI. I'm not sure which test-dep brought that in.  https://github.com/MacPython/pandas-wheels/pull/63/commits/b3ed55fe5f52262c69c60af52a89cfe4efd6f5fd removes a few now-unnecessary dependencies.

**Comment by TomAugspurger** [comment]
https://travis-ci.org/MacPython/pandas-wheels/jobs/597826930 passed on 3.8 with a few warnings

```
  /venv/lib/python3.8/site-packages/pandas/tests/frame/test_alter_axes.py:240: SyntaxWarning: "is" with a literal. Did you mean "=="?
5224    False if (keys[0] is "A" and keys[1] is "A") else drop  # noqa: F632
5225
5226

  /venv/lib/python3.8/site-packages/pandas/io/json/_json.py:159: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
5258    return dumps(
5259
5260
```

Merging on green.

**Comment by jbrockmendel** [comment]
Looks like the 3.5 build is errorring out early:

```
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
```

**Comment by TomAugspurger** [comment]
Hopefully fixed by the other PR. Will pull it in to see.

**Comment by jbrockmendel** [comment]
It looks like the failing build uses OSX 10.6 (Snow Leopard) which was released in 2009.  We'd probably be OK bumping that if it turns out to be the problem

**Pull request merged**
