### PR TITLE
test 1.1.x - DO NOT MERGE

### PR DESCRIPTION
**Pull request by simonjayhawkins**
cc @TomAugspurger

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
still have failures here. these have started appearing

```
=========================== short test summary info ===========================
FAILED test_venv/lib/site-packages/pandas/tests/io/excel/test_style.py::test_styler_to_excel[xlwt]
= 1 failed, 63973 passed, 7373 skipped, 1044 xfailed, 14 warnings in 579.59s (0:09:39) =
```

**Comment by TomAugspurger** [comment]
If it's a pytest-xdist crash then perhaps just restart that job once the others finish..

**Comment by simonjayhawkins** [comment]
> If it's a pytest-xdist crash then perhaps just restart that job once the others finish..

I don't have access here but also failed on previous run.

once https://github.com/MacPython/pandas-wheels/pull/94 and https://github.com/pandas-dev/pandas/pull/35809 we should be passing here.

will wait and see!

**Comment by TomAugspurger** [comment]
If it's easier, you can also skip here by updating https://github.com/MacPython/pandas-wheels/blob/86f860c13db84ec1b159651f1b40af0f3bd477b5/config.sh#L36.

**Comment by simonjayhawkins** [comment]
yes currently do that, but probably cleaner to be consistent with other 32bit test failures

**Comment by simonjayhawkins** [comment]
@TomAugspurger things looking more healthy here so I think ready to tag the release.

only failure here
```
=========================== short test summary info ===========================
FAILED test_venv/lib/site-packages/pandas/tests/io/parser/test_common.py::test_file_descriptor_leak[c_high]
= 1 failed, 64044 passed, 7331 skipped, 1018 xfailed, 16 warnings in 416.67s (0:06:56) =
```
I though this was fixed (passed in https://github.com/MacPython/pandas-wheels/pull/93/commits/43d088894fe24d1e084fd829849809963e8555db after xdist pin), but must be a flaky test.

We could add that to skip list in PR for RLS1.1.1 to build wheels or restart?

cc @jreback

**Comment by TomAugspurger** [comment]
Maybe best to just skip it here? If the build doesn't pass a wheel won't be uploaded.

**Comment by TomAugspurger** [comment]
@matthew-brett can you or anyone else who has access here add @simonjayhawkins to the pandas-builders team so he can restart builds if necessary?

**Comment by simonjayhawkins** [comment]
> Maybe best to just skip it here? If the build doesn't pass a wheel won't be uploaded.

will open another PR for that (the auto generated one) in the meantime https://github.com/MacPython/pandas-wheels/pull/94 should be merged?

**Comment by TomAugspurger** [comment]
Done.

**Pull request closed without merging**
