### PR TITLE
CI: Use plain arm not the graviton ones

### PR DESCRIPTION
**Pull request by lithomas1**

### CODE REVIEW

**Comment by datapythonista** [comment]
Looks like this is working now. Travis support told me that the problem should be fixed, but I tried reruning the release build and still failed.

**Comment by lithomas1** [comment]
@datapythonista 
When this gets to all green, I think we can try uploading the arm64 wheels.

**Comment by lithomas1** [comment]
Unfortunately, I think the aarch64 jobs are still being flaky and getting killed or failing.

I'm a little confused about why arm64-gravitron isn't working since arm64 and arm64 gravitron should be the same thing(I think there was a post here https://blog.travis-ci.com/2020-09-11-arm-on-aws#Quick%20tips:~:text=to%20%E2%80%98full%2Dvm%E2%80%99-,Quick%20tips,-You%20have%20to).

**Comment by datapythonista** [comment]
Ah, good to know. Thanks a lot for the help with this. Does this need to be merged for the wheels to be generated, or are we having wheels also for PR runs?

**Comment by lithomas1** [comment]
> Ah, good to know. Thanks a lot for the help with this. Does this need to be merged for the wheels to be generated, or are we having wheels also for PR runs?

PR builds don't get uploaded.

**Review by datapythonista — APPROVED** [review]
Cool, I guess we can merge this on green then.

**Comment by lithomas1** [comment]
Looks like the arm builds are crashing sadly, probably because of the high memory tests.

I think I'll self-merge this when its ready, and I'll ping you when everything is green and uploaded to save you some time.

**Comment by lithomas1** [comment]
@datapythonista I think the ARM builds are back online since the one I started a couple hours ago finally finished. You might want to try uploading again now.

**Comment by datapythonista** [comment]
All good, uploaded them to pypi. Thanks a lot for the help!

**Pull request closed without merging**
