### PR TITLE
Update multibuild to support stripping wheels

### LINKED ISSUE #24: Update multibuild to version that strips binaries in wheels
On the next release, please update the multibuild submodule to https://github.com/matthew-brett/multibuild/commit/b2748e5d4d2ae6e45b130bdf8e24361083341e9a or newer. This should reduce the size of the Pandas wheels from 27M to 11M by excluding unnecessary debug symbols.

ref https://github.com/pandas-dev/pandas/issues/19531

### PR DESCRIPTION
**Pull request by xhochy**
Closes #24 

Travis build will probably fail as this PR should not have the permission to upload the wheels in the final step.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
We skip upload on PRs.

Should there be anything in the log output indicating that the strip ran / was successful? I skimmed and didn't see anything.

**Comment by xhochy** [comment]
Yes there should be `-Wl,-strip-all` in the lines that call `gcc` which is actually not there.

I have to investigate why it was in my branch but not here :(
```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -L/usr/local/include -fPIC -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/opt/python/cp27-cp27mu/lib/python2.7/site-packages/numpy/core/include -I/opt/python/cp27-cp27mu/include/python2.7 -c pandas/_libs/sparse.c -o build/temp.linux-x86_64-2.7/pandas/_libs/sparse.o -Wno-unused-function
```

**Comment by jreback** [comment]
@xhochy shall we revive this?

**Comment by simonjayhawkins** [comment]
closing, xref https://github.com/MacPython/pandas-wheels/pull/144#issuecomment-882656611

**Pull request closed without merging**
