### PR TITLE
Pin anaconda-client build dependency

### PR DESCRIPTION
**Pull request by janaknat**
Pin the anaconda-client commit hash used for Travis pip installs to avoid a problematic dependency addition to requirements.txt.

See: https://github.com/MacPython/scipy-wheels/pull/116 for more details.

### CODE REVIEW

**Comment by janaknat** [comment]
@TomAugspurger @jreback This fixes the upload issue for python 3.8 and python 3.9 aarch64 wheels.

**Comment by janaknat** [comment]
@simonjayhawkins Any thoughts on this PR?

**Comment by AWSjswinney** [comment]
This change would be really helpful. Thanks for working on this!

**Comment by jreback** [comment]
is this not a released version? if not why not

**Comment by janaknat** [comment]
The python 3.8 and 3.9 arm64 wheel builds fail in the upload step because of an issue with anaconda client. This Travis-CI config is very similar to scipy and they also had the same issue. This PR fixes the problem and should allow for aarch64 python 3.8 and python 3.9 releases.

The issue started because of a change in the requirements.txt of a wheel anaconda-client uses. https://github.com/MacPython/scipy-wheels/pull/116 shows how the scipy project dealt with it.

**Comment by jreback** [comment]
ok

**Pull request merged**
