### PR TITLE
skip test_float_precision_options, test_rolling_var_numerical_issues and test_rolling_skew_kurt_large_value_range

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref https://github.com/pandas-dev/pandas/issues/36429#issuecomment-732921416

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@jreback

**Comment by simonjayhawkins** [comment]
@jreback i'll close this for a bit, since there are other 32bit tests failing, test_rolling_var_numerical_issues and test_rolling_skew_kurt_large_value_range that are failing on all linux 32bit,  linux py_3.7_32, linux py_3.8_32 and linux py_3.9_32 (and also aarch)

Unlike test_float_precision_options which was failing on windows py_3.8_32 and windows py_3.9_32 (not testing for 3.7[1]), i'm surprised these other 32bit failures aren't appearing on our ci. (It would be easier to debug/fix if they were)

so I think we should first investigate why these failures are not appearing on our ci before attempting any fixes.

[1] It appears that the py37 can be re-enabled will open a PR shortly

It also appears that we no longer need to skip test_file_descriptor_leak (and can unpin pytest-dist https://github.com/MacPython/pandas-wheels/issues/95) - will open a PR shortly for this

given the planned tidy up, I think the best course of action is to skip the 3 32bit tests here for now so that nightly wheels build.

Once the other PRs are complete and merged will reopen this.

**Comment by simonjayhawkins** [comment]
> there are other 32bit tests failing, test_rolling_var_numerical_issues and test_rolling_skew_kurt_large_value_range that are failing on all linux 32bit, linux py_3.7_32, linux py_3.8_32 and linux py_3.9_32 (and also aarch)

xref https://github.com/pandas-dev/pandas/issues/37398

**Comment by jreback** [comment]
ok sure

**Comment by simonjayhawkins** [comment]
@jreback I will be merging this before the end of the day so that the nightly builds of the 32bit wheels succeeds.

**Pull request merged**
