### PR TITLE
CI: Update multibuild

### PR DESCRIPTION
**Pull request by lithomas1**
Update multibuild to unblock possible universal2/PyPy support.
cc @simonjayhawkins.

P.S. It looks like the build flaked out again. I know that this might be asking a lot, but would it be possible to obtain write access so that I can restart the builds?

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
> I know that this might be asking a lot, but would it be possible to obtain write access so that I can restart the builds?

I don't have those permissions


> It looks like the build flaked out again.

restarted

**Comment by lithomas1** [comment]
No biggie, thanks anyways for restarting the build.

**Comment by lithomas1** [comment]
@simonjayhawkins Green.

**Comment by simonjayhawkins** [comment]
> Update multibuild to unblock possible universal2/PyPy support.

we are the other projects on MacPython with this?

**Comment by simonjayhawkins** [comment]
and can we close https://github.com/MacPython/pandas-wheels/pull/25

**Comment by lithomas1** [comment]
Numpy has both types on PyPI. #25 should be closed, since our multibuild submodule should already include it.

**Comment by simonjayhawkins** [comment]
Thanks @lithomas1

**Pull request merged**
