### PR TITLE
change NP_BUILD_DEP for 3.7

### PR DESCRIPTION
**Pull request by simonjayhawkins**
xref https://github.com/pandas-dev/pandas/issues/37784#issuecomment-732911912

### CODE REVIEW

**Comment by simonjayhawkins** [comment]
@TomAugspurger @jreback

**Comment by jreback** [comment]
actually we should merge this anyways. we have a min of 1.16.x on 1.1.5 anyhow.

**Comment by simonjayhawkins** [comment]
> actually we should merge this anyways. we have a min of 1.16.x on 1.1.5 anyhow.

the min for 1.1.x is 1.15.4 https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.1.0.html#increased-minimum-versions-for-dependencies.

does the NP_BUILD_DEP affect the numpy support of the built wheel, or is NP_BUILD_DEP just for the environment to build the wheel. we test the minimum version in ci on pandas.

also I missed changing the numpy versions for the aarch travis builds, so these are still failing on nightly but should be fixed by #38087 even if not changed here.

**Comment by jorisvandenbossche** [comment]
> does the NP_BUILD_DEP affect the numpy support of the built wheel, or is NP_BUILD_DEP just for the environment to build the wheel. we test the minimum version in ci on pandas.

It does affect the wheel, as we need to build the wheel with the lowest supported numpy version, so a user can install it in an environment with this numpy version (a wheel build with a newer numpy would error in such an environment)

So if this patch is only for 1.2.0, that seems fine, but if it is also used for 1.1.5, it should be reverted I think (I don't know how the branching in this repo works)

**Comment by simonjayhawkins** [comment]
> (I don't know how the branching in this repo works)

everything is built from master (on this branch) so nightly uses pandas master and commits uses the latest pandas (i.e. 1.1.4)

**Comment by jorisvandenbossche** [comment]
Some time ago, there was apparently a "maintenance" branch (still exists, but not updated anymore), which might make it easier to test both the bugfix releases as testing the wheels on latest master at the same time.  
(not very familiar with this repo, though, so don't know if the above is true in practice)

**Comment by jorisvandenbossche** [comment]
Because with the current setup, the daily cron job has constantly been testing 1.1.4, instead of the latest master or 1.1.x ?

**Comment by simonjayhawkins** [comment]
no the cron job uses pandas master.

**Comment by simonjayhawkins** [comment]
see https://anaconda.org/scipy-wheels-nightly/pandas/files

**Comment by simonjayhawkins** [comment]
we don't have any nightly builds for 1.1.x and therefore I have been opening a PR to test 1.1.x in advance of release.

generally have been issues with 32 bit since we went for a long period without 32bit testing on our ci. Was hoping that this release would be smoother since https://github.com/pandas-dev/pandas/pull/35898, but 32bit failures are still occurring here. We may need to revisit out setup on pandas ci. see also https://github.com/MacPython/pandas-wheels/pull/113#issuecomment-734786736

**Comment by jorisvandenbossche** [comment]
How should I interpret https://travis-ci.com/github/MacPython/pandas-wheels/builds then? That shows that the cron job is failing using the last commit on master, which is using the 1.1.4 tag

**Comment by jorisvandenbossche** [comment]
Ah, we might be talking passed each other, as you maybe mean the Azure pipeline cron?

**Comment by simonjayhawkins** [comment]
It was green yesterday after the push, (used pandas 1.1.4) and then went red after the cron job ran (used pandas master)

**Comment by jorisvandenbossche** [comment]
BTW, since you have been working on this quite a bit, it might be good to document somewhat somewhere the overview of how this repo works / how we use it.

**Comment by simonjayhawkins** [comment]
> How should I interpret https://travis-ci.com/github/MacPython/pandas-wheels/builds then? That shows that the cron job is failing using the last commit on master, which is using the 1.1.4 tag

that link is not showing the latest (cron) job https://github.com/MacPython/pandas-wheels/runs/1461897488

**Comment by jorisvandenbossche** [comment]
Well, that link *is* showing the latest cron jobs, but on travis, which I assume we are not using anymore? (as I said above, we might have been talking about different things, as I was looking at the travis config)

**Comment by simonjayhawkins** [comment]
> So if this patch is only for 1.2.0, that seems fine, but if it is also used for 1.1.5, it should be reverted I think (I don't know how the branching in this repo works)

to be safe, maybe we should revert for now.

**Comment by simonjayhawkins** [comment]
> Well, that link _is_ showing the latest cron jobs (you can check the dates), but on travis, which I assume we are not using anymore? (as I said above, we might have been talking about different things, as I was looking at the travis config)

it is confusing because we have recently started to use travis again but for the arm builds. (that's the reason I overlooked updating it in this PR)

**Comment by simonjayhawkins** [comment]
I guess the cron job for travis is configured independently (maybe in travis?) and is on a different schedule to the azure builds (cron job configured in code) on https://github.com/MacPython/pandas-wheels where the lastest build is shown as red, but the travis job is still green so that agrees with https://travis-ci.com/github/MacPython/pandas-wheels/builds

**Comment by jorisvandenbossche** [comment]
> I guess the cron job for travis is configured independently (maybe in travis?) 

I think you can configure it in travis itself, yes. But so, it running just the latest commit. In Azure, there is some logic to not use the BUILD_COMMIT for the corn jobs:

https://github.com/MacPython/pandas-wheels/blob/fb668ef2e6568d1f12d2c374b9051c761084ead1/azure/posix.yml#L37-L38

but on travis, such logic is not present as far as I see. So in the travis yaml, you would need to put eg `BUILD_COMMIT=1.1.x` after each bug fix release, so keep testing the latest state of the 1.1.x branch

**Comment by simonjayhawkins** [comment]
looking at the travis config, you could be right about travis not building nightly against pandas master. It looks like the relevant code maybe commented out. will look some more. The arm build was recently added in https://github.com/MacPython/pandas-wheels/pull/99

**Comment by simonjayhawkins** [comment]
> `BUILD_COMMIT=1.1.x` after each bug fix release, so keep testing the latest state of the 1.1.x branch

probably `BUILD_COMMIT=master` to be consistent with azure

**Comment by simonjayhawkins** [comment]
> also I missed changing the numpy versions for the aarch travis builds, so these are still failing on nightly but should be fixed by #38087 even if not changed here.

changing NP_BUILD_DEP (and NP_TEST_DEP) for travis https://github.com/MacPython/pandas-wheels/pull/111/commits/e9a011afce5faffc0f6f68d8cf7f6e5ff5f12b87 is causing the tests to fail with master (i.e pandas 1.2) which is concerning.

https://travis-ci.com/github/MacPython/pandas-wheels/jobs/449632801

so maybe need to open an issue for this as well as the nightly wheel build issue.

for now, aarch (and 32bit) wheels are not a blocker for 1.2.0rc0 release.

**Comment by simonjayhawkins** [comment]
another minor issue is that don't have a clean skip for 3.6 in travis (like in azure)

This may not be relevant once 1.1.5 is released as we will be deleting the 3.6 environments.

**Comment by simonjayhawkins** [comment]
> so maybe need to open an issue for this as well as the nightly wheel build issue.

missed that there is already an open issue for this https://github.com/MacPython/pandas-wheels/issues/102

**Pull request merged**
