### PR TITLE
add mac wheels for 10.9 / 64b only

### LINKED ISSUE #42: mac wheels should be built for 10.9
as discussed in #37, pandas wheels should really be built for macOS 10.9. The current wheels, built for 10.6, have some extensions which link to `stdlibc++`, which has been deprecated since macOS 10.9, and may no longer be installed in some case on 10.14 systems (see https://github.com/pandas-dev/pandas/issues/23424)

A quick hack solution would be to revert https://github.com/MacPython/pandas-wheels/pull/38.  This would build wheels which would break if installed on systems < 10.9. Although its highly unlikely anyone is still running such old versions of macOS.

A cleaner fix would be based on https://github.com/matthew-brett/multibuild/pull/224, which is in for review. As will as generating wheels which pip would correctly reject on pre-10.9 systems, it would reduce the gigantic filenames, from:

```
pandas-0.24.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
```
to

```
pandas-0.24.0-cp37-cp37m-macosx_10_9_x86_64.macosx_10_10_x86_64.whl
```
which appeals to my sense of tidyness

### PR DESCRIPTION
**Pull request by robbuckley**
resolves #42 for master
cherry pick from daily 978fdc29b2a7a1d91e3d73443a26308f3d389465
also align build matrix with daily

* update multibuild submodule to support building osx 10.9 / 64b only wheels
* make 10.9 builds the default for osx
* move override of pandas MACOSX_DEPLOYEMENT_TARGET from .travis.yml to config.sh for osx
* remove python 2.7 builds

### CODE REVIEW

**Comment by robbuckley** [comment]
@jreback ping. This updates `multibuild` the the same version as daily, and changes the macOS python 2.7 and 3.6 build to target macOS 10.9+.

**Comment by jreback** [comment]
so master needs to be updated to remove 2.7 support
is the daily one ok? if so then we can just make master match it

**Comment by robbuckley** [comment]
yes, i think daily is OK (modulo periodic breakages due to churn on pandas master). I've copied the build matrix from daily, so: remove all 2.7 builds, and removes the linux 3.5 32b build. So theres just one 32b build now (for 3.6). The `numpy` min version is higher on daily - i havent carried that across.

**Comment by robbuckley** [comment]
@jreback the 3 macos wheels from my fork install OK for me locally.

All builds have a string of `INTERNALERROR>` lines, although they dont seem to affect the ability to build wheels, and they are on the head of `master` too. They seem to be backtraces for these 2 exceptions:
```
INTERNALERROR>   File "<remote exec>", line 119, in pytest_collectreport
INTERNALERROR> AttributeError: '_HookRelay' object has no attribute 'pytest_report_to_serializable'
```
and
```
INTERNALERROR>   File "/Users/travis/build/MacPython/pandas-wheels/venv/lib/python3.6/site-packages/execnet/gateway_base.py", line 707, in send
INTERNALERROR>     raise IOError("cannot send to {!r}".format(self))
INTERNALERROR> OSError: cannot send to <Channel id=1 closed>
```

**Comment by TomAugspurger** [comment]
The version of pytest being picked up (3.8.2) is quite old. That may be the source of the collection error.

That's being set at https://github.com/MacPython/pandas-wheels/blob/master/.travis.yml#L87.

**Comment by TomAugspurger** [comment]
I'd prefer to move this setting to pandas. We should have an `extra_requires` for pandas, and install `pandas[test]` which installs the necessary versions of pytest and hypothesis.

**Comment by TomAugspurger** [comment]
I already opened https://github.com/pandas-dev/pandas/issues/25593 for that :) I'll make a PR to pandas, and we can use it here.

**Comment by robbuckley** [comment]
Sure, but that shouldn’t block this PR from being merged, should it? Let me know if I need to do anything more here

**Comment by TomAugspurger** [comment]
The tests aren't actually being run right now. https://travis-ci.org/MacPython/pandas-wheels/jobs/549413737#L4004

I'll make another PR updating the pytest install and then we can re-run this on top.

**Comment by robbuckley** [comment]
Now you mention that, I do remember thinking the wheels were building quite a bit quicker than I remembered...-:)

**Comment by robbuckley** [comment]
@TomAugspurger I can get most of the tests running on master by allowing `pytest` to use the latest (removing the pin to 3.8.2) plus #49 which is already on master. There are still a couple of issues with this:
- in all builds it looks like all markers are being flagged with `PytestUnknownMarkWarning`. This is new in `pytest` 4.5.0. My trials builds pulled 4.6.4. Not sure if this is an issue
- 1 collection error in each of the 2.7 linux builds, although these dont trigger a travis fail:

2.7 linux 64b

```
_________________ ERROR collecting tests/resample/test_base.py _________________
In test_resample_interpolate_all_ts: function uses no argument '_index_factory'
```

2.7 linux 32b

```
_________________ ERROR collecting tests/resample/test_base.py _________________
In test_resample_loffset_arg_type_all_ts: function uses no argument '_series_name'
```

**Comment by TomAugspurger** [comment]
Sorry for the delay. Looking now. We don't need to worry about 2.7 anymore.

**Comment by TomAugspurger** [comment]
Whoops, I didn't realize this was also syncing master with daily. I did that over in https://github.com/MacPython/pandas-wheels/pull/53

@robbuckley can you confirm that things look OK on master now? We have

- https://github.com/MacPython/pandas-wheels/blob/master/.travis.yml#L8
- https://github.com/MacPython/pandas-wheels/blob/master/.travis.yml#L49
- https://github.com/MacPython/pandas-wheels/blob/master/config.sh#L7

**Comment by robbuckley** [comment]
@TomAugspurger no problem. The `multibuild` submodule version needs to be updated to match the one on daily. Then the macOS py36 and py37 wheels will be generated for macOS 10.9+ rather than 10.6+. That was the original intent of this PR. 

Also, you have removed the linux py35 32b build, is that intentional? It was added to master fairly recemtly, in https://github.com/MacPython/pandas-wheels/pull/35

i can update this PR to do either/both, but first let me know.

Everything else looks good.

**Comment by robbuckley** [comment]
I built wheels off the current master, and confirmed the mac ones are wrong (they are all 10.6+ dual arch). I've pushed the `multibuild` change to this PR, with this change on my fork the 3.6 and 3.7 wheels build OK as 10.9+ 64b

**Comment by robbuckley** [comment]
ping @TomAugspurger @jreback, any chance of getting this merged?

**Comment by TomAugspurger** [comment]
Thanks. I'll followup on your comment in https://github.com/MacPython/pandas-wheels/pull/48#issuecomment-508572146

**Pull request merged**
