### PR TITLE
CI: Bump VM Image Versions in Azure

### PR DESCRIPTION
**Pull request by lithomas1**
Mirroring some changes we made in the other repo.

~~Not bumping windows since we are redistributing some dlls from Visual Studio 2017, and it might be risky to upgrade Visual Studio.~~
See below

### CODE REVIEW

**Comment by lithomas1** [comment]
I think we can probably bump windows for 1.4, since the rc will probably catch the errors(if any exist).

**Comment by lithomas1** [comment]
cc @simonjayhawkins

**Comment by simonjayhawkins** [comment]
> since the rc will probably catch the errors(if any exist).

The nightly builds are from master, so issues should be caught before the rc.

**Comment by lithomas1** [comment]
@simonjayhawkins Greenish.
IIUC, as long as the DLL version and the compiler toolchain version match, we should be fine.

**Comment by simonjayhawkins** [comment]
@lithomas1 i've restarted the failing job to be sure. Also reopened https://github.com/MacPython/pandas-wheels/pull/135 to check current build status.

if both green will merge this and then rereun #135.

Should we maybe add something to the other section of 1.3.1 just in case there are issues so that users can more easily troubleshoot?

I assume this is a low-risk change. if not should we wait till finished with 1.3.x before merging?

**Comment by simonjayhawkins** [comment]
> if both green will merge this and then rereun #135.

both green.

**Comment by jreback** [comment]
i guess need to revert this for the 1.3.x patch release builds

**Pull request merged**
